name: CI
on: [ push, pull_request ]

jobs:
  build:
    name: Run
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        dc: [ dmd-latest, ldc-latest ]
        exclude:
          - os: macos-latest
            dc: dmd-latest  # dmd is not available on macOS ARM runners

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2
      with:
        # Requiried for codecov action
        fetch-depth: 2

    - uses: dlang-community/setup-dlang@v1
      with:
        compiler: ${{ matrix.dc }}

    - name: 'Build & Test'
      shell: bash
      run: |
        dub test --compiler=$DC -b unittest-cov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        flags: unittests
